train_configs = {
    "dset_name": "EMPIAR_10045_train",
    "base_path": "/shared/home/v_brian_bosho/SampleDatasets/EMPIAR_10045",
    "coord_path": "/shared/home/v_brian_bosho/SampleDatasets/EMPIAR_10045/coords",
    "coord_format": ".coords",
    "tomo_path": "/shared/home/v_brian_bosho/SampleDatasets/EMPIAR_10045/data_std",
    "tomo_format": ".mrc",
    "num_cls": 1,
    "label_type": "gaussian",
    "label_diameter": 11,
    "ocp_type": "sphere",
    "ocp_diameter": "23",
    "norm_type": "standardization",
    "label_name": "gaussian11",
    "label_path": "/shared/home/v_brian_bosho/SampleDatasets/EMPIAR_10045/gaussian11",
    "ocp_name": "data_ocp",
    "ocp_path": "/shared/home/v_brian_bosho/SampleDatasets/EMPIAR_10045/data_ocp",
    "model_name": "ResUNet",
    "train_set_ids": "0",
    "val_set_ids": "0",
    "batch_size": 8,
    "patch_size": 72,
    "padding_size": 12,
    "lr": 0.001,
    "max_epochs": 60,
    "seg_thresh": 0.5,
    "gpu_ids": "0,1"
}
